name: deploy-book

# Ejecutar esto cuando la rama master o main cambie
on:
  push:
    branches:
    - master
    - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3

    # Instalar dependencias
    - name: Configurar Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt

    # (opcional) Caché de tus cuadernos ejecutados entre ejecuciones
    - name: Caché de cuadernos ejecutados
      uses: actions/cache@v3
      with:
        path: _build/.jupyter_cache
        key: jupyter-book-cache-${{ hashFiles('requirements.txt') }}

    # Construir el libro
    - name: Construir el libro
      run: |
        jupyter-book build .

    # Subir el HTML del libro como un artefacto
    - name: Subir artefacto
      uses: actions/upload-artifact@v3  # Actualizado a la última versión
      with:
        path: "_build/html"

    # Desplegar el HTML del libro en GitHub Pages
    - name: Desplegar en GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
